export const goods = [
    {
        year: '2012',
        dollar: 1.78,
        minimumWage: 886.5,
        goods: [
            {
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/5030354/5030354_yan-febbe6-1650x1650.jpg',
                title: 'Çaykur Rize Turist Çay',
                subtitle: '1000 gr.',
                price: 35.25,
            },
            {
                image: '',
                title: "Yumurtacım Omega 3 10'Lu M Boy Yumurta",
                subtitle: '53-62 G',
                price: 10.5,
            },
            { image: '', title: 'Pınar Süt', subtitle: '1 L', price: 7.45 },
            {
                image: '',
                title: 'Tahsildaroğlu Ezine Klasik İnek Peyniri',
                subtitle: '600gr',
                price: '51.75',
            },
            { image: '', title: 'Torku Yoğurt ', subtitle: '1.5 Kg', price: 13.95 },
            { image: '', title: 'Dana Kıymalık', subtitle: '1 KG.', price: 59.95 },
            { image: '', title: 'Söke Un', subtitle: '1 KG.', price: '8.75' },
            { image: '', title: 'Bizim Paket Margarin', subtitle: '250 G', price: 4.5 },
            { image: '', title: 'Yayla Nohut', subtitle: '2 KG.', price: 25.45 },
            { image: '', title: 'Yayla Pilavlık Pirinç', subtitle: '2 KG.', price: 29.75 },
            { image: '', title: 'Banvit Piliç Izgara Tava', subtitle: '1 KG.', price: 47.9 },
            { image: '', title: 'Domates', subtitle: '1 KG.', price: 3.99 },
            { image: '', title: 'Soğan Kuru Dökme', subtitle: '1 KG.', price: 0.99 },
            { image: '', title: 'Patates Ödemiş', subtitle: '1 KG.', price: 2.45 },
        ],
    },
    {
        year: '2021',
        dollar: 8.73,
        minimumWage: 3577,
        goods: [
            {
                id: 45,
                image: 'https://zamsepeti.com/_assets/img/urun/ev1.png',
                title: 'Ev Kirası',
                subtitle: '2+1',
                price: 1200,
            },
            {
                id: 0,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03111303/03111303-949450-1650x1650.jpg',
                title: 'Çaykur Rize Turist Çay',
                subtitle: '1000 gr.',
                price: 35.25,
            },
            {
                id: 1,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/20001980/20001980-46b5da-1650x1650.jpg',
                title: "Yumurtacım Omega 3 10'Lu M Boy Yumurta",
                subtitle: '53-62 G',
                price: 10.5,
            },
            {
                id: 2,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11010010/11010010-1ae231-1650x1650.jpg',
                title: 'Pınar Süt',
                subtitle: '1 L',
                price: 7.45,
            },
            {
                id: 3,
                image: 'https://cdnd-tr.ceptesok.com/product/1000x1000/df75f_Inek_Peyniri_350_Gr.jpg',
                title: 'Mis Ezine İnek Peyniri',
                subtitle: '350 Gr',
                price: 15.65,
            },
            {
                id: 4,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/12500700/12500700-91e1f6-1650x1650.png',
                title: 'Torku Yoğurt ',
                subtitle: '1.5 Kg',
                price: 13.95,
            },
            {
                id: 5,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/25010073/25010073-560231-1650x1650.jpg',
                title: 'Dana Kıymalık',
                subtitle: '1 KG.',
                price: 59.95,
            },
            {
                id: 6,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05010401/05010401-c4c14f-1650x1650.jpg',
                title: 'Söke Un',
                subtitle: '1 KG.',
                price: '8.75',
            },
            {
                id: 7,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/4201901/4201901-bcb8ea-1650x1650.jpg',
                title: 'Bizim Paket Margarin',
                subtitle: '250 G',
                price: 4.5,
            },
            {
                id: 8,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01049971/01049971-d3bb65-1650x1650.jpg',
                title: 'Yayla Nohut',
                subtitle: '2 KG.',
                price: 25.45,
            },
            {
                id: 9,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01011127/yayla-pilavlik-pirinc-2-kg-749f03-1650x1650.jpg',
                title: 'Yayla Pilavlık Pirinç',
                subtitle: '2 KG.',
                price: 29.75,
            },
            {
                id: 11,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040101/46040101-dacafe-1650x1650.jpg',
                title: 'Banvit Piliç Izgara Tava',
                subtitle: '1 KG.',
                price: 47.9,
            },
            {
                id: 12,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28080000/domates-kg-c7462d-1650x1650.jpg',
                title: 'Domates',
                subtitle: '1 KG.',
                price: 3.99,
            },
            {
                id: 13,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28420000/sogan-kuru-dokme-kg-25131e-1650x1650.jpg',
                title: 'Soğan Kuru Dökme',
                subtitle: '1 KG.',
                price: 0.99,
            },
            {
                id: 14,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28290036/28290036-6a65f9-1650x1650.jpg',
                title: 'Patates',
                subtitle: '1 KG.',
                price: 2.45,
            },
            {
                id: 15,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/4110401/4110401-1eac4c-1650x1650.jpg',
                title: 'Yudum Ayçiçek Yağı ',
                subtitle: '1 L.',
                price: 27.9,
            },
            {
                id: 41,
                image: 'https://zamsepeti.com/_assets/img/urun/benzin.png',
                title: 'Benzin',
                subtitle: '1 L.',
                price: 8,
            },
        ],
    },
    {
        year: '2022',
        dollar: 17.7102,
        minimumWage: 5500,
        goods: [
            {
                id: 45,
                image: 'https://zamsepeti.com/_assets/img/urun/ev1.png',
                title: 'Ev Kirası',
                subtitle: '2+1',
                price: 2000,
            },
            {
                id: 16,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/03111303/03111303-949450-1650x1650.jpg',
                title: 'Çaykur Rize Turist Çay',
                subtitle: '1000 gr.',
                price: 69.9,
            },
            {
                id: 21,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/20001980/20001980-46b5da-1650x1650.jpg',
                title: "Yumurtacım Omega 3 10'Lu M Boy Yumurta",
                subtitle: '53-62 G',
                price: 24.5,
            },
            {
                id: 22,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/11010010/11010010-1ae231-1650x1650.jpg',
                title: 'Pınar Süt',
                subtitle: '1 L',
                price: 19.5,
            },
            {
                id: 23,
                image: 'https://cdnd-tr.ceptesok.com/product/1000x1000/df75f_Inek_Peyniri_350_Gr.jpg',
                title: 'Mis Ezine İnek Peyniri 350 Gr',
                subtitle: '350 Gr',
                price: 29.95,
            },
            {
                id: 24,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/12500700/12500700-91e1f6-1650x1650.png',
                title: 'Torku Yoğurt ',
                subtitle: '1.5 Kg',
                price: 32.25,
            },
            {
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/25010073/25010073-560231-1650x1650.jpg',
                title: 'Dana Kıymalık',
                subtitle: '1 KG.',
                price: 109.75,
            },
            {
                id: 25,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/05010401/05010401-c4c14f-1650x1650.jpg',
                title: 'Söke Un',
                subtitle: '1 KG.',
                price: 15.5,
            },
            {
                id: 26,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/4201901/4201901-bcb8ea-1650x1650.jpg',
                title: 'Bizim Paket Margarin',
                subtitle: '250 G',
                price: 12.5,
            },
            {
                id: 27,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01049971/01049971-d3bb65-1650x1650.jpg',
                title: 'Yayla Nohut',
                subtitle: '2 KG.',
                price: 82.9,
            },
            {
                id: 28,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/01011127/yayla-pilavlik-pirinc-2-kg-749f03-1650x1650.jpg',
                title: 'Yayla Pilavlık Pirinç',
                subtitle: '2 KG.',
                price: 39.9,
            },
            {
                id: 31,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/46040101/46040101-dacafe-1650x1650.jpg',
                title: 'Banvit Piliç Izgara Tava',
                subtitle: '1 KG.',
                price: 99.9,
            },
            {
                id: 32,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28080000/domates-kg-c7462d-1650x1650.jpg',
                title: 'Domates',
                subtitle: '1 KG.',
                price: 11.95,
            },
            {
                id: 323,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28420000/sogan-kuru-dokme-kg-25131e-1650x1650.jpg',
                title: 'Soğan Kuru Dökme',
                subtitle: '1 KG.',
                price: 10.95,
            },
            {
                id: 33,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/28290036/28290036-6a65f9-1650x1650.jpg',
                title: 'Patates',
                subtitle: '1 KG.',
                price: 12.9,
            },
            {
                id: 34,
                image: 'https://migros-dali-storage-prod.global.ssl.fastly.net/sanalmarket/product/4110401/4110401-1eac4c-1650x1650.jpg',
                title: 'Yudum Ayçiçek Yağı ',
                subtitle: '1 L.',
                price: 49.9,
            },
            {
                id: 35,
                image: 'https://zamsepeti.com/_assets/img/urun/benzin.png',
                title: 'Benzin',
                subtitle: '1 L.',
                price: 20,
            },
        ],
    },
];
